// Module declarations for static image imports (`import photo from "*.webp"`).
//
// `next-env.d.ts` provides these, but it is generated by the build and not
// committed, and CI typechecks before it builds. Referencing the types here
// keeps `tsc --noEmit` passing on a fresh checkout.
/// <reference types="next/image-types/global" />
